# Generated by Django 4.1.5 on 2023-04-05 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_model',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 6, 1, 20, 3, 809904)),
        ),
    ]
